config/routes.rb
Rails.application.routes.draw do

  # Devise Routes
  devise_for :users

  # User Admin Routes
  constraints(lambda { |request| !MobileSubdomain.matches?(request) }) do
    scope :module => :admin do

      get  '/see/:uuid/messages/:last_id' => 'slide_show#new_messages'
      get '/see/:uuid/delete' => 'slide_show#delete_message'
      get  '/see/:uuid' => 'slide_show#show', as: :event_slideshow
     # get  '/download/:id' => 'event#download_all_polaroids', as: :event_download_all_polaroids
      resources :events do
        resources :messages
      end

      # Root of site
      root 'welcome#index', as: :admin_root
    end
  end

  # User Mobile Routes
  constraints(lambda { |request| MobileSubdomain.matches?(request) }) do
    scope :module => :mobile do

      get  '/messages/check-event-code/:event_code' => 'messages#check_event_code'
      get  '/messages/polaroid/:id' => 'messages#show_polaroid', as: :show_polaroid
    #  get  '/messages/download-polaroid/:id' => 'messages#download_polaroid', as: :download_polaroid
      resources :messages

      # Root of site
      root 'messages#new', as: :mobile_root
    end
  end

end

app/controllers/admin/welcome_controller.rb
class Admin::WelcomeController < ApplicationController

  def index
    flash.now[:notice] = "Hello " + current_user.email
  end
end

app/views/admin/welcome/index.html.erb
<div style="text-align: center">Welcome to SnappyGuests!</div>

<div id="indexMenuContainer" style="width: 600px; margin-left:auto; margin-right: auto; padding: 20px;">
    <%= link_to "Events", events_path, :class => 'btn btn-block btn-primary'  %>
    <%= link_to "Users", users_path, :class => 'btn btn-block btn-primary'  %>

</div>