config/routes.rb
Rails.application.routes.draw do

  # Devise Routes
  devise_for :users

  # User Admin Routes
  constraints(lambda { |request| !MobileSubdomain.matches?(request) }) do
    scope :module => :admin do

      get  '/see/:uuid/messages/:last_id' => 'slide_show#new_messages'
      get '/see/:uuid/delete' => 'slide_show#delete_message'
      get  '/see/:uuid' => 'slide_show#show', as: :event_slideshow
     # get  '/download/:id' => 'event#download_all_polaroids', as: :event_download_all_polaroids
      resources :events do
        resources :messages
      end

      # Root of site
      root 'welcome#index', as: :admin_root
    end
  end

  # User Mobile Routes
  constraints(lambda { |request| MobileSubdomain.matches?(request) }) do
    scope :module => :mobile do

      get  '/messages/check-event-code/:event_code' => 'messages#check_event_code'
      get  '/messages/polaroid/:id' => 'messages#show_polaroid', as: :show_polaroid
    #  get  '/messages/download-polaroid/:id' => 'messages#download_polaroid', as: :download_polaroid
      resources :messages

      # Root of site
      root 'messages#new', as: :mobile_root
    end
  end

end

app/models/event.rb
class Event < ActiveRecord::Base

  has_many :messages
  has_many :user_events
  has_many :users, through: :user_events

  before_create :init_uuid

  validates_presence_of :title, :code, :start_date, :end_date
  validates_numericality_of :latitude, :if => Proc.new{|event| event.latitude.present?}
  validates_numericality_of :longitude, :if => Proc.new{|event| event.longitude.present?}

  private

  def init_uuid
    self.uuid = UUID.new.generate
  end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController

  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

=begin
  def download_all_polaroids
    if (File.exists?("tmp/download_all_polaroids/"))
      puts "[ ok ] Deleting existing tmp/download_all_polaroids/ directory"
      FileUtils.remove_dir("tmp/download_all_polaroids/")
    end

    # Create folder
    FileUtils.mkpath("tmp/download_all_polaroids/")

    @event.messages.each do |message|
      FileUtils.cp_r(download_polaroid_path(message), "tmp/download_all_polaroids/#{message.id}.png")
    end
  end
=end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :code, :start_date, :end_date, :latitude, :longitude, :status)
    end
end

app/views/admin/events/_form.html.erb
<%= simple_form_for @event, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :title %>
  <%= error_span(@event[:title]) %>
  <%= f.input :code %>
  <%= error_span(@event[:code]) %>
  <%= f.input :start_date %>
  <%= error_span(@event[:start_date]) %>
  <%= f.input :end_date %>
  <%= error_span(@event[:end_date]) %>
  <%= f.input :latitude %>
  <%= error_span(@event[:latitude]) %>
  <%= f.input :longitude %>
  <%= error_span(@event[:longitude]) %>
  <%= f.input :status %>
  <%= error_span(@event[:status]) %>
  <%= f.input :uuid %>
  <%= error_span(@event[:uuid]) %>

  <div class="well">
      <%= f.button :submit, :class => 'btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                    events_path, :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/admin/events/edit.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/events/index.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:code) %></th>
      <th><%= model_class.human_attribute_name(:start_date) %></th>
      <th><%= model_class.human_attribute_name(:end_date) %></th>
      <th><%= model_class.human_attribute_name(:latitude) %></th>
      <th><%= model_class.human_attribute_name(:longitude) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:uuid) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.id, event_path(event) %></td>
        <td><%= event.title %></td>
        <td><%= event.code %></td>
        <td><%= event.start_date %></td>
        <td><%= event.end_date %></td>
        <td><%= event.latitude %></td>
        <td><%= event.longitude %></td>
        <td><%= event.status %></td>
        <td><%= event.uuid %></td>
        <td><%=l event.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_event_path(event), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      event_path(event),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_event_path,
            :class => 'btn btn-primary' %>

app/views/admin/events/new.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/events/show.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @event.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:code) %>:</strong></dt>
  <dd><%= @event.code %></dd>
  <dt><strong><%= model_class.human_attribute_name(:start_date) %>:</strong></dt>
  <dd><%= @event.start_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:end_date) %>:</strong></dt>
  <dd><%= @event.end_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:latitude) %>:</strong></dt>
  <dd><%= @event.latitude %></dd>
  <dt><strong><%= model_class.human_attribute_name(:longitude) %>:</strong></dt>
  <dd><%= @event.longitude %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @event.status %></dd>
  <dt><strong><%= model_class.human_attribute_name(:uuid) %>:</strong></dt>
  <dd><%= @event.uuid %></dd>
  <dt><strong><%= model_class.human_attribute_name(:messages) %>:</strong></dt>
  <dd><%= link_to @event.messages.count, event_messages_path(@event) %></dd>
  <dt><strong>Viewing URL:</strong></dt>
  <dd><%= link_to event_slideshow_path(@event.uuid), event_slideshow_path(@event.uuid), :target => "_blank" %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")), events_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")), edit_event_path(@event), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              event_path(@event),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>