config/routes.rb
Rails.application.routes.draw do

  # Devise Routes
  devise_for :users

  # User Admin Routes
  constraints(lambda { |request| !MobileSubdomain.matches?(request) }) do
    scope :module => :admin do

      get  '/see/:uuid/messages/:last_id' => 'slide_show#new_messages'
      get '/see/:uuid/delete' => 'slide_show#delete_message'
      get  '/see/:uuid' => 'slide_show#show', as: :event_slideshow
     # get  '/download/:id' => 'event#download_all_polaroids', as: :event_download_all_polaroids
      resources :events do
        resources :messages
      end

      # Root of site
      root 'welcome#index', as: :admin_root
    end
  end

  # User Mobile Routes
  constraints(lambda { |request| MobileSubdomain.matches?(request) }) do
    scope :module => :mobile do

      get  '/messages/check-event-code/:event_code' => 'messages#check_event_code'
      get  '/messages/polaroid/:id' => 'messages#show_polaroid', as: :show_polaroid
    #  get  '/messages/download-polaroid/:id' => 'messages#download_polaroid', as: :download_polaroid
      resources :messages

      # Root of site
      root 'messages#new', as: :mobile_root
    end
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :event

  validates_presence_of :event_id, :message => "could not be found"
  validates_presence_of :email

  has_attached_file :photo, :styles => { :large => "1000x1000>", :medium => "281x220>", :thumb => "100x100>"}, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  after_post_process :save_photo_dimensions

  ROTATE_CLOCKWISE = 90
  ROTATE_ANTICLOCKWISE = -90

  def save_photo_dimensions
      geometry = Paperclip::Geometry.from_file(self.photo.queued_for_write[:original])
    #  puts "#{image_exif_data[:orientation].inspect}"
      self.photo_width = geometry.width.to_i
      self.photo_height = geometry.height.to_i
      begin
        image_exif_data = EXIFR::JPEG.new(self.photo.queued_for_write[:original].path).exif
        if (image_exif_data[:orientation] == EXIFR::TIFF::RightTopOrientation)
          self.photo_height = geometry.width.to_i
          self.photo_width = geometry.height.to_i
        end
        rescue
      end

=begin
      if (image_exif_data[:orientation] == EXIFR::TIFF::RightTopOrientation)
        degrees = ROTATE_CLOCKWISE
      elsif (image_exif_data[:orientation] == EXIFR::TIFF::LeftBottomOrientation)
        degrees = ROTATE_ANTICLOCKWISE
      else
        puts "Not rotating #{self.photo.queued_for_write[:original]}"
        return
      end

      image = (Magick::Image.read(self.photo.queued_for_write[:original])).first
      #image.rotate(degrees).write("#{file.split('.').first}_rotated.jpg")
      image.rotate(degrees).write("#{self.photo.queued_for_write[:original]}")
=end

  end

end

app/controllers/admin/messages_controller.rb
class Admin::MessagesController < ApplicationController
  before_action :set_event
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = @event.messages.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = @event.messages.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = @event.messages.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to event_message_path(@event, @message), notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to event_message_path(@event, @message), notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @message.destroy

    redirect_to event_messages_path(@event)
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:event_id])
    end

    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:body, :user_id, :photo, :event_id)
    end
end

app/controllers/mobile/application_controller.rb
class Mobile::ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout 'mobile'
end

app/controllers/mobile/messages_controller.rb
class Mobile::MessagesController < Mobile::ApplicationController

  layout 'mobile'

  skip_before_action :verify_authenticity_token

  before_action :set_step, :except => [:check_event_code]
  before_action :set_event
  before_action :set_message, only: [:show, :delete, :show_polaroid, :download_polaroid]
  before_action :set_email, only: [:create]

  def new
    @message = Message.new(:user => current_user)
    @message.email = session[:email] if session[:email].present?
    @message.event = Event.find(session[:event_id]) if session[:event_id].present?
  end

  def create
    @message = Message.new(message_params)

    if !@event
      @step = "email_step"
    else
      session[:event_id] = @event.id
    end

    @message.event = @event

    respond_to do |format|
      if @message.save
        format.html { redirect_to message_path(@message), notice: 'Message was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def show
    @page_id = "show_message"
  end

  def index
    redirect_to new_message_path
  end

  def check_event_code
  end

  def show_polaroid
    @page_id = "download_polaroid"
  end

=begin
  def download_polaroid
    #kit = IMGKit.new(render_to_string(:show_polaroid), :quality => 50)
    kit = IMGKit.new("http://m.snappyguests.com/messages/polaroid/#{params[:id]}")
   # kit.stylesheets << "#{Rails.root}/app/assets/stylesheets/imgkit/application.css"
   # kit.javascripts << "#{Rails.root}/app/assets/javascripts/imgkit/application.js"
    img =  kit.to_img(:png)
    #send_file img.to_s.gsub("\u0000", ''), type: 'image/png', disposition: 'inline'
    send_data(img, :type => "image/jpeg", :disposition => 'inline')
  end
=end

  private

  def set_step
    @step = "upload_step"
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find_by_code(params[:event_code]) if params[:event_code]
  end

  def set_message
    @message = Message.find(params[:id])
  end

  def set_email
    session[:email] = params[:message][:email] if params[:message][:email]
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def message_params
    params.require(:message).permit(:photo, :email, :body, :event_code)
  end

end

app/helpers/message_helper.rb
module MessageHelper

  def polaroid_font_size(message_body)
    font_size = '5vmin'
    line_height= '5vmin'

=begin
    font_size = 30
    line_height= 30

    if (message_body.length < 18)
      font_size = line_height = 30
    elsif message_body.length >= 52
      font_size = line_height = 18
    elsif message_body.length >= 18
      font_size = 20
      line_height = 30

      if message_body.length >= 18
        line_height = 20
      end
    end
=end


    if (message_body.length < 18)
        font_size = line_height = '5vmin'
    end
    if message_body.length >= 18
        font_size = line_height = '4vmin'
    end
    if message_body.length >= 48
        font_size = line_height = '3vmin'
    end

    return "font-size: #{font_size}; line-height: #{line_height}"
  end

end

app/views/mobile/messages/_email.html.erb
<!-- Start of email input step -->
<div role="main" class="ui-content email_step" data-theme="a" style="<%= @step == "email_step" ? "" : "display:none"%>">

  <!-- Fade in contents after slide -->
  <div class="contents" style="<%= @step == "email_step" ? "" : "display:none"%>">
    <label>Event Code</label>
    <%= text_field_tag :event_code, (@message.event.present? ? @message.event.code : nil), placeholder: 'LOVE', data: {'clear-btn' => true}, :required => true %>
    <br/>
    <label>Your Email</label>
    <%= f.input :email, label: false, input_html: {'data-clear-btn' => true}, placeholder: 'name@email.com', type: :email, :required => true %>
    <br/>
    <p>
      These details will be stored so you do not have to re-enter them
    </p>
  </div>

</div><!-- /content -->

app/views/mobile/messages/_message.html.erb
<!-- Start of second page -->
<div role="main" class="ui-content message_step" style="<%= @step == "message_step" ? "" : "display:none"%>">

  <div class="contents" style="<%= @step == "message_step" ? "" : "display:none"%>">

    <!-- Maintain an aspect ratio of width x height (9:10), but do not exceed width of 750px -->
    <div id="polaroid_container">
        <div id="photo">
          <div id="black_bg"><%= image_tag "", :class => "display_photo" %></div>

          <div id="message">
            <%= f.input :body, label: false, as: :text, placeholder: 'Your message', maxlength: 75, :input_html => {:class => "polaroid_message", :data => {:autogrow => false}} %>
            <div id="chars-remaining"></div>
          </div>
        </div>
        <div id="polaroid_bg">&nbsp;
        </div>
    </div>

  </div>

</div><!-- /content -->

app/views/mobile/messages/_page_one.html.erb
<!-- Start of second page -->
<div data-role="page" id="page_one" data-theme="d" data-dom-cache="true">
  <div data-role="header" data-theme="b" data-position="fixed">
    <%= image_tag("logo.png") %>
  </div>

  <!-- Image Picker -->
  <div style="width: 0; height: 0; overflow: hidden;">
    <%= f.file_field :photo, :accept => "image/*" %>
  </div>

  <div role="main" class="ui-content" data-theme="d">
    <div id="photo_container">
        <div id="polaroid_background"></div>
        <%= image_tag 'upload_your_photo.png' %>
        <div id="polaroid_mask" class="image_upload"></div>
    </div>
  </div>

  <div data-role="footer" data-theme="b" data-position="fixed">
    <div class="ui-grid-solo">
      <div class="ui-block-a">
        <a id="photo_button" href="#" data-role="button" class="image_upload">Select Photo</a>
      </div>
    </div>
  </div>
</div>

app/views/mobile/messages/_page_three.html.erb
<!-- Start of second page -->
<div data-role="page" id="page_three" data-theme="d" data-dom-cache="true">

  <div data-role="header" data-theme="b" data-position="fixed">
    <a href="#page_two" data-icon="back" data-transition="slide" data-direction="reverse">Back</a>
    <h1>Email</h1>
    <div class="ui-btn-right">
      <%= f.submit 'Done', :data => {"icon" => "check", "theme" => "b"} %>
    </div>
  </div>

  <div role="main" class="ui-content" data-theme="d">
      <div data-theme="c" class="ui-body ui-body-c ui-corner-all margin">
        Since you are not signed in enter your email to upload your photo
        <%= f.input :email, label: false, placeholder: 'name@email.com', type: :email %>
    </div>

  </div><!-- /content -->

</div><!-- /page -->

app/views/mobile/messages/_page_two.html.erb
<!-- Start of second page -->
<div data-role="page" id="page_two" data-theme="d" data-dom-cache="true">

  <div data-role="header" data-theme="b" data-position="fixed">
    <a href="#page_one" data-icon="back" data-transition="slide" data-direction="reverse">Back</a>
    <h1>Caption it!</h1>
    <a href="#page_three" data-icon="check" data-transition="slide">Save</a>
  </div>

  <div role="main" class="ui-content">

    <div id="photo_container">
      <div id="polaroid_background"></div>
      <img id="display_photo" src="" alt="snapshot"/>
      <div id="polaroid_mask">
        <div id="photo_message">
          <%= f.input :body, label: false, as: :text, placeholder: 'Your message here' %>
        </div>
      </div>
    </div>

  </div><!-- /content -->

</div><!-- /page -->

app/views/mobile/messages/_upload.html.erb
<div class="upload_step" style="<%= !@step || @step == "upload_step" ? "" : "display:none"%>">
  <div style="width: 0; height: 0; overflow: hidden;">
    <%= f.file_field :photo, :accept => "image/*" %>
  </div>

  <div role="main" class="ui-content" data-theme="d">

    <!-- Maintain an aspect ratio of width x height (9:10), but do not exceed width of 750px -->
    <div id="polaroid_container">
      <div id="photo">
        <div id="black_bg">
            <img src="/images/chalkboard.png" width="100%" height="100%"/>
        </div>
        <div id="message"> <div class="polaroid_message">Upload Your Photo</div> </div>
      </div>
      <div id="polaroid_bg"></div>
    </div>

  </div>
</div>

app/views/mobile/messages/check_event_code.js.erb
$('#event_code-error').remove();
<% if @event %>
  $('#event_code').parent(".ui-input-text").removeClass('error');
  $('#event_code').parent(".ui-input-text").append('<label id="event_code-error" class="ui-icon-check ui-btn-icon-left error valid" for="event_code"> Event found!</label>');
  $('#event_code').removeClass("invalid_code");
<% else %>
  $('#event_code').addClass("invalid_code");
  $('#event_code').parent(".ui-input-text").addClass('error');
  $('#event_code').parent(".ui-input-text").append('<label id="event_code-error" class="ui-icon-alert ui-btn-icon-left error" for="event_code"> Event not found.</label>');
<% end %>

app/views/mobile/messages/new.html.erb
<% content_for(:theme) { "d" } %>

<div id="upload_page" data-role="page" data-theme="w">

  <%= simple_form_for(@message, :html => { :multipart => true, "data-ajax" => "false",  novalidate: true }) do |f| %>

      <!-- Headers -->
      <div data-role="header" data-theme="b" data-position="fixed" data-tap-toggle="false" class="upload_step" style="<%= !@step || @step == "upload_step" ? "" : "display:none"%>">
        <%= image_tag("logo.png") %>
      </div>

      <div data-role="header" data-theme="b" data-position="fixed" data-tap-toggle="false" class="message_step" style="<%= @step == "message_step" ? "" : "display:none"%>">
        <a id="message_back_button" data-icon="back">Back</a>
        <h1>Caption it!</h1>
        <a id="message_save_button" data-icon="check">Save</a>
      </div>

      <div data-role="header" data-theme="b" data-position="fixed" data-tap-toggle="false" class="email_step" style="<%= @step == "email_step" ? "" : "display:none"%>">
        <a id="email_back_button" data-icon="back">Back</a>
        <h1>Email</h1>
        <div class="ui-btn-right">
          <%= f.submit 'Done', :data => {"icon" => "check", "theme" => "b"} %>
        </div>
      </div>

        <%= render :partial => "mobile/shared/errors", :locals => {:f => f, :object => @message} %>
        <%= f.input :event_id, :value => @message.event_id, :as => :hidden %>
        <%= render 'upload', :f => f %>
        <%= render 'message', :f => f %>
        <%= render 'email', :f => f %>

      <!-- Footer -->
      <div data-role="footer" data-theme="b" data-position="fixed" data-tap-toggle="false" class="upload_step" style="<%= !@step || @step == "upload_step" ? "" : "display:none"%>">
        <div class="ui-grid-solo">
          <div class="ui-block-a">
            <a id="photo_button" href="#" data-role="button" class="image_upload">Select Photo</a>
          </div>
        </div>
      </div>
  <% end %>

</div>

app/views/mobile/messages/show.html.erb
<!-- Start of second page -->
<div id="show_message" data-role="page" data-theme="w">
  <div data-role="header" data-theme="b" data-position="fixed">
    <%= image_tag("logo.png") %>
    <%= link_to 'Upload New', "#{mobile_root_path}", :data => {'transition' => 'slide', 'prefetch' => true, :theme => 'a'}, :class => 'ui-btn-right' %>
  </div>

  <div role="main" class="ui-content" data-theme="d">

    <!-- Maintain an aspect ratio of width x height (9:10), but do not exceed width of 750px -->
    <div id="polaroid_container" class="loadingImages">
        <div id="photo">
          <div id="black_bg">
            <%= image_tag @message.photo(:large), :onload=>"fadeInImage(this),aspectFit(this)", :class=> "fadeInImage loading display_photo" %>
          </div>
          <div id="message"> <div class="polaroid_message"><%=@message.body%></div> </div>
        </div>
        <div id="polaroid_bg">&nbsp; </div>
      </div>
    </div>

  </div>

</div>

<% if @page_id == "show_message" %>
    <%= content_for :header do %>
    <script>
        $(document).on('pageload', '#show_message', function (event) {
            setTimeout(function () {
                $.mobile.loading('show', {
                    text: "Image successfully uploaded!",
                    textVisible: true,
                    textonly: true,
                    theme: 'a',
                    html: ""
                });


                setTimeout(function () {
                    $.mobile.loading('hide');
                }, 2000);

            }, 0);
        });
    </script>
    <% end %>
<% end %>

app/views/mobile/messages/show_polaroid.html.erb
<!-- Start of second page -->
<div role="main" class="ui-content message_step">

  <div class="contents">

    <!-- Maintain an aspect ratio of width x height (9:10), but do not exceed width of 750px -->
    <div id="polaroid_container">
      <div id="photo">
        <div id="black_bg"><%= image_tag @message.photo(:large), :id => "current_image", :class => "display_photo", :onload => "scaleImage('#current_image', #{@message.photo_width}, #{@message.photo_height})" %></div>

        <div id="message">
          <div style='<%=polaroid_font_size(@message.body)%>'><%= @message.body %></div>
          <div id="chars-remaining"></div>
        </div>
      </div>
      <div id="polaroid_bg">&nbsp;
      </div>
    </div>

  </div>

</div><!-- /content -->